version: '3'
services:
  autobuild:
    image: 'firstandthird/docker-autobuild:1.0.0'
    ports:
      - "8080"
    environment:
      GITHUB_TOKEN: '${GITHUB_TOKEN}'
      SLACK_HOOK: '${BUILDER_SLACK_HOOK}'
      SECRET: '${BUILDER_SECRET}'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME/.docker:/home/app/.docker"
      - "${BUILDER_CONFIG}:/home/app/src/conf/default-builder.yml"
    networks:
      - "traefik-net"
    deploy:
      replicas: 2
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
