version: '3'
services:
  autobuild:
    image: 'firstandthird/docker-autobuild:1.2.0'
    ports:
      - "8080"
    environment:
      GITHUB_TOKEN: '${BUILDER_GITHUB_TOKEN}'
      SLACK_HOOK: '${BUILDER_SLACK_HOOK}'
      SECRET: '${BUILDER_SECRET}'
      RAPPTOR_CONFIG_URL: '${BUILDER_CONFIG_URL}'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME/.docker:/home/app/.docker"
    networks:
      - "traefik-net"
    deploy:
      replicas: 2
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
networks:
  traefik-net:
    external: true
